
server {

    listen 8501;

    location / {
        root /usr/share/nginx/html;
    }

    # location /tde {
    #     proxy_pass http://172.16.101.96:10999/tde;
    # }

    # location /intent/ {
    #     proxy_pass http://172.16.101.116/;
    # }

}
