FROM harbor.emotibot.com/bfop/tde_app:base

COPY docker/conf/nginx.conf /etc/nginx/nginx.conf
COPY docker/conf/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

COPY docker/entrypoint.sh .
COPY dist .

ENTRYPOINT ["./entrypoint.sh"]
